name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    name: PHP
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 5.4
          - 5.5

    services:
      redis:
        image: redis

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis

      - name: Composer
        run: |
          composer selfupdate
          composer install --prefer-source
